exporting requirePriorUseWashout
darwin-eu-dev/DrugUtilisation pull request #472
Opened 2024-07-01 11:42 UTC by xihang-chen

2024-07-02 13:20 UTC, xihang-chen commented
hey @catalamarti I've put these two lines at the beginning of the script 
```
if ((sumcounts(cohort) == 0) & (name !=tableName(cohort))){
    cli::cli_abort("Cohort is empty so washout cannot be applied.
                   Suggest rechecking the cohort.")
  }

  if (washout == 0 & (name !=tableName(cohort))){
    cli::cli_abort("Washout specified is 0 meaning nothing will be applied.
                   Suggest rechecking the washout.")
  }
```
to prevent a situation where for example cohort is empty (as the main if statement will bypass this) and name has been specified to something else.

Let me know if this looks not okay and I will amend accordingly.

2024-07-02 22:13 UTC, catalamarti requested changes
thanks @xihang-chen some minor comments

2024-07-02 22:13 UTC, catalamarti commented on R/requirePriorUseWashout.R
> +      dplyr::compute(name = uniqueTmpName(), temporary = FALSE, overwrite = TRUE)
could we drop this intermediate table at the end of the function?

2024-07-02 22:13 UTC, catalamarti commented on R/requirePriorUseWashout.R
> +  if ((sumcounts(cohort) == 0) & (name !=tableName(cohort))){
could we use cohortCounts instead of sumcounts?

2024-07-02 22:13 UTC, catalamarti commented on R/requirePriorUseWashout.R
> +    cli::cli_abort("Cohort is empty so washout cannot be applied.
would be nice if this is a warning instead of an error and we return the same cohort. In general we throw error only if the inputs are incorrect

2024-07-03 10:09 UTC, catalamarti commented on R/requirePriorUseWashout.R
> +                                   washout,
cohortId argument
washout -> priorUseWashout

2024-07-03 10:14 UTC, catalamarti commented on R/requirePriorUseWashout.R
> +    cli::cli_abort("Washout specified is 0 meaning nothing will be applied.
same

2024-07-03 10:15 UTC, catalamarti commented on R/requirePriorUseWashout.R
> +  if (sumcounts(cohort) > 0 & washout > 0) {
not needed

2024-07-03 10:20 UTC, catalamarti commented on tests/testthat/test-summariseTreatment.R
> +  cdm <- mockDrugUtilisation()
put connectionDetails back

2024-07-09 08:35 UTC, catalamarti approved these changes
thanks @xihang-chen

2024-07-09 08:35 UTC, merged