update
darwin-eu-dev/DrugUtilisation pull request #481
Opened 2024-07-03 09:54 UTC by ilovemane

2024-07-04 08:50 UTC, ilovemane commented
Hey Marti, I have to comment out some test related to summariseIndication. Since we nee to re-code that function I guess?

2024-07-04 09:15 UTC, catalamarti requested changes
hi @ilovemane some small changes that would be needed, thank you very much

2024-07-04 09:15 UTC, catalamarti commented on R/addIndication.R
> +                          cdm = attr(x ,"cdm_reference"),
can we eliminate the cdm argument?

2024-07-04 09:15 UTC, catalamarti commented on R/addIndication.R
> +    CDMConnector::computeQuery()
can we use dplyr::compute(name = ..., temporary = ...)? if we need to compute inside the function could we make all the intermediate tables permanents and we delete them?

2024-07-04 09:15 UTC, catalamarti commented on R/addIndication.R
> +                          indexDate = "cohort_start_date") {
could we have a name argument so that we compute the table to where we need it. default name = NULL (temporary table)

2024-07-05 11:32 UTC, catalamarti approved these changes

2024-07-05 11:32 UTC, merged

2024-07-05 11:32 UTC, catalamarti commented
thanks @ilovemane